Generic Processors
HubSpot/jinjava pull request #1045
Opened 2023-04-07 13:43 UTC by boulter

I decided to just implement a more generic version of https://github.com/HubSpot/jinjava/pull/1044 so we could easily add processors for pre and post execution of nodes and now filters. In the future we could add tags and functions to the builder.

2023-04-07 14:02 UTC, jasmith-hs requested changes
I like the idea of making this usable across more operations in Jinjava. Are there any filters, in particular, you're interested in timing?

2023-04-07 14:25 UTC, boulter commented
> I like the idea of making this usable across more operations in Jinjava. Are there any filters, in particular, you're interested in timing?

I'm not really concerned with filters right now, but it was an easy demonstration for how to use processors for functionality besides nodes.

2023-04-07 14:26 UTC, boulter commented on src/main/java/com/hubspot/jinjava/lib/filter/Filter.java
> +    }
yeah, I know it won't catch everything, but it does catch most. I added a comment to explain that.

2023-04-07 14:27 UTC, boulter commented on src/main/java/com/hubspot/jinjava/JinjavaConfig.java
> +     */
I did like the idea of not storing the `nodePreProcessor`, so I removed it in favor of building on the existing `Processors` with a new builder method.

2023-04-08 03:25 UTC, jasmith-hs commented on src/main/java/com/hubspot/jinjava/lib/filter/Filter.java
> +    }
You could instead add processors within `JinjavaInterpreterResolver.invoke` or some other place within the ELResolver code to get around this.

2023-04-09 00:14 UTC, boulter commented
I've removed the filter processors for now since I don't need them.

2023-04-09 00:14 UTC, merged

2026-03-06 21:20 UTC, tes966 commented on src/main/java/com/hubspot/jinjava/lib/filter/Filter.java
> +    }
https://github.com/HubSpot/jinjava/pull/1045?new_signup=true?new_signup=true#discussion_r1161054773