Debug Undefined Feature to echo back Uknown tokens.
HubSpot/jinjava pull request #1150
Opened 2024-01-19 17:51 UTC by abarrafo

Inspired by this [PR - Render back unresolved tokens](https://github.com/HubSpot/jinjava/pull/1072). Implemented instead with features as suggested by @jasmith-hs and named `ECHO_UNDEFINED` . I originally wanted to call it DEBUG_UNDEFINED to get close to this [feature in jinja2](https://github.com/pallets/jinja/blob/3fd91e4d11bdd131d8c12805177dbe74d85e7b82/tests/test_api.py#L354), but that offers a bit more.

2024-01-19 18:46 UTC, jasmith-hs requested changes
Thank you for taking a look at this

2024-01-19 18:46 UTC, jasmith-hs commented on src/main/java/com/hubspot/jinjava/lib/expression/DefaultExpressionStrategy.java
> +  }
If the expression renders an empty string, `{{ '' }}` then we should allow an empty string to be output.

If instead we moved this to line 24:
```java
if (var == null && feat.isActive(interpreter.getContext()) {
  return new RenderedOutputNode(master.getImage());
}
```
We can make sure that we're only echoing back when it's undefined.

Also, make sure that you run `mvn prettier:write` to format the code, as we have tab spacing set to `2` for this project.

2024-01-19 21:47 UTC, merged

2024-01-19 23:03 UTC, marius-diumia commented
thank you both @jasmith-hs & @abarrafo for helping with this and merging

2024-01-31 13:34 UTC, abarrafo commented
Hey @jasmith-hs , just curious on what your release lifecycle is? Any idea on when the next release will make is into maven central? Thanks so much