Apply custom operators at `mul` precedence
HubSpot/jinjava pull request #895
Opened 2022-07-20 17:44 UTC by tkindy

Closes #893 

Currently, our custom operators like `|` and `is` bind tighter than unary operators. This means `-1 is integer` incorrectly evaluates like `-(1 is integer)`, leading to an error when Jinjava tries to make `true` negative.

This PR pulls our custom operators up from the `unary` level of the JUEL grammar to the `mul` level. This means they bind tighter than `mul` but less tightly than `unary`. From my testing, this aligns with Jinja's precedence rules.

2022-07-20 18:50 UTC, tkindy commented on src/main/java/com/hubspot/jinjava/el/ext/ExtendedParser.java
> -  protected AstNode value() throws ScanException, ParseException {
This diff is really weird, but basically I moved the parsing of our custom operators from the `default` of `value` to the `default` of `mul`.

2022-07-21 16:13 UTC, jasmith-hs requested changes
assertThat(interpreter.render("{{ (-5 * -4 | abs) }}")).isEqualTo("-20");

I think the filter operation should be at the same level as `unary` rather than the same level as mul.
Might make sense to add a new `filter(boolean required)` method and have `mul()` point to that instead of `unary()` and have the filter method call unary and do the `|` and `is` logic

2022-07-21 19:49 UTC, tkindy commented
> `assertThat(interpreter.render("{{ (-5 * -4 | abs) }}")).isEqualTo("-20");`

Thanks for the extra test case! I confirmed Jinja indeed returns -20 here.

![image](https://user-images.githubusercontent.com/2991842/180302696-17be6567-29a2-415a-95e2-6ba1c1047e5c.png)

> I think the filter operation should be at the same level as `unary` rather than the same level as mul.

I think you mean filters should bind tighter than `mul` but less tightly than `unary`; that is, that we should introduce a new level of precedence. They currently bind at the same level as `unary`, and that's the problem.

Your implementation suggestion sounds good to me, I'll try that out.

2022-07-21 20:13 UTC, tkindy commented on src/main/java/com/hubspot/jinjava/el/ext/ExtendedParser.java
> -  protected AstNode value() throws ScanException, ParseException {
With my recent changes, the diff makes more sense now.

2022-07-21 20:14 UTC, jasmith-hs approved these changes
LGTM

2022-07-21 20:27 UTC, merged